language: node_js
install: npm install --no-optional
git: depth: 1
node_js:
- 10
- 9
- 8
- 7
- 6
- 5
- 4
jobs:
  include:
  - stage: coverage
    install: npm install istanbul coveralls
    script: npm run coverage
    after_success: cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
  - stage: deploy
    install: skip
    script: skip
    deploy:
      provider: npm
      email: ivo.putzer@gmail.com
      api_key:
        secure: QfM6/3XM0YGbzEwo/3Bdbpg2njXPGH5qhS+FohWxO1ZcSjLbZnAowmalMSTmcwL4lKkzF5bfU0zJ3J6p++Om04CPLlIDXbqKw9XpnqcwoCR147bBBwRbIxE5L0Zd9i14Z4Qb9WHJSsMzeB12nnUvaDeyQ+IK3kaMiYyGP1z3zS0=
      on:
        repo: $TRAVIS_REPO_SLUG
        branch: master
  allow_failures:
  - node_js: 5
  - node_js: 4
